name: dav_server
description: "DAV Server GUI"
publish_to: 'none'
version: 1.3.1

environment:
  sdk: ^3.5.4

dependencies:
  clipboard: ^0.1.3
  ffi: ^2.1.3
  file_picker: ^10.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.7.2
  msix: ^3.16.12
  path: ^1.9.0
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.2
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: "PuHui"
      fonts:
        - asset: fonts/AlibabaPuHuiTi-3-Regular.ttf
  assets:
    - assets/

msix_config:
  display_name: DAV Server
  publisher_display_name: ZhouCheng
  identity_name: ZhouCheng.DAVServer
  msix_version: 1.3.0.0
  logo_path: assets/icon.png
  trim_logo: false
  capabilities: internetClient, internetClientServer
  languages: zh-cn, zh-tw, en-us
  publisher: # Publisher HERE
  store: true